[package]
name = "toboggan-core"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["std"]
std = ["alloc", "jiff/std", "serde/std", "once_cell/std", "pulldown-cmark"]
alloc = ["jiff/alloc", "serde/alloc", "getrandom", "once_cell/critical-section"]
js = ["jiff/js", "getrandom/js", "uuid/js"]
openapi = ["utoipa"]
test-utils = []

[dependencies]
jiff = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["serde", "v4"] }
once_cell = { workspace = true }
getrandom = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }
pulldown-cmark = { workspace = true, optional = true }
derive_more = {workspace = true, features = ["add"]}

[lints]
workspace = true
