[package]
name = "toboggan-core"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true, features = ["full"] }
jiff = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
