[branch]
name = "{{name | slugify}}"

[branch.validation]

[[branch.fields]]
name = "name"
required = true
type = "text"

[branch.fields.validation]
min_length = 3

[commit]
title = """
{{type}}
{%- if scope -%}
    ({{scope}})
{%- endif -%}
{%- if breaking -%}
    !
{%- endif -%}
: {{subject | first_upper | trim_end_matches(pat='.') }}"""
description = "{{description | wrap(size=72) }}"
auto_signed = false
auto_add = false

[commit.validation]
# pattern = "^(feat|fix|docs|style|refactor|perf|test|build|chore|revert)(\\(.\\))?!?: (.){1, 72}$"

[[commit.fields]]
name = "type"
prompt = "Select the type of change that you're committing"
required = true
type = "list"
allow_custom_value = false

[[commit.fields.values]]
value = "feat"
description = "âœ¨ a new feature"

[[commit.fields.values]]
value = "fix"
description = "ğŸ› a bug fix"

[[commit.fields.values]]
value = "docs"
description = "ğŸ“ documentation"

[[commit.fields.values]]
value = "style"
description = "ğŸ¨ code-stylish change like formatting"

[[commit.fields.values]]
value = "refactor"
description = "â™»ï¸ code refactoring"

[[commit.fields.values]]
value = "perf"
description = "âš¡ï¸ performance improvements"

[[commit.fields.values]]
value = "test"
description = "ğŸ§ª adding missing test or correct existing tests"

[[commit.fields.values]]
value = "build"
description = "ğŸ‘· changes related to project build"

[[commit.fields.values]]
value = "ci"
description = "ğŸ’š changes related to CI/CD"

[[commit.fields.values]]
value = "chore"
description = "ğŸ”§ other changes"

[[commit.fields.values]]
value = "revert"
description = "âª revert a previous commit"

[[commit.fields]]
name = "breaking"
prompt = "Are there any breaking changes?"
default = false
required = true
type = "confirm"
affirmative = "Yes ğŸ’¥"
negative = "No"

[[commit.fields]]
name = "scope"
prompt = "What is the scope of this change?"
description = "\te.g. component or file name"
required = false
type = "text"

[commit.fields.validation]

[[commit.fields]]
name = "subject"
prompt = "If applied, this commit will ..."
description = "Short, imperative tense description of the change"
required = true
type = "text"

[commit.fields.validation]

[[commit.fields]]
name = "description"
prompt = "Description of the change"
required = false
type = "text"

[commit.fields.validation]
