[env]
RUST_LOG = "info"

TOBOGGAN_HOST = "0.0.0.0"

# Android SDK
ANDROID_HOME = "/Users/igorlaborie/Library/Android/sdk"
ANDROID_SDK_ROOT = "/Users/igorlaborie/Library/Android/sdk"
ANDROID_NDK_HOME = "/Users/igorlaborie/Library/Android/sdk/ndk/29.0.14206865"

[settings]
experimental = true
cargo = { binstall = true }

[tools]
"cargo:bacon" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-nextest" = "0.9"
"cargo:wasm-pack" = "latest"
"npm:rolldown-vite" = "latest"
"npm:vite" = "latest"
"npm:wasm-opt" = "latest"
swiftlint = "latest"
"npm:@stoplight/spectral-cli" = "latest"
"cargo:cargo-ndk" = "latest"
