[package]
name = "toboggan-web"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
toboggan-core = { path = "../toboggan-core", features = ["alloc", "js"] }

[lints]
workspace = true
