[package]
name = "toboggan-tui"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
toboggan-core = {path = "../toboggan-core", features = ["std"]}

ratatui = "0.29"
crossterm = "0.28"
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = "0.21"
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
clap = { workspace = true, features = ["env", "derive"] }
futures = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }

[lints]
workspace = true