[package]
name = "toboggan-desktop"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
toboggan-core = { path = "../toboggan-core", features = ["std"] }
toboggan-client = { path = "../toboggan-client" }

iced = { workspace = true }
lucide-icons = { version = "0.541.0", features = ["iced"] }
iced_aw = { version = "0.12.2", features = ["card", "badge"] }

tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
async-stream = "0.3"

anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
