[package]
name = "toboggan-desktop"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
toboggan-core = { path = "../toboggan-core", features = ["std"] }
iced = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dirs = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
futures-util = { workspace = true }

[lints]
workspace = true
